Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'educacion', to: 'pages#educacion'
  get 'radio', to: 'pages#radio'
  get 'servicios', to: 'pages#servicios'
  get 'audiovisual', to: 'pages#audiovisual'
  get 'revolturas', to: 'pages#revolturas'
  get 'fpn-vera', to: 'pages#fpnvera'
  get 'educacion/filosofiaparaninos', to: 'pages#filosofiaparaninos'
  get 'educacion/planetaneta', to: 'pages#planetaneta'
  get 'educacion/elmisteriodelaspreguntassinrespuesta', to: 'pages#elmisteriodelaspreguntassinrespuesta'
  get 'educacion/comosaberquenoeresunrobot', to: 'pages#comosaberquenoeresunrobot'
  get 'educacion/robotropolis', to: 'pages#robotropolis'
  get 'educacion/habitarelarte', to: 'pages#habitarelarte'
  get 'educacion/esculpireltiempo', to: 'pages#esculpireltiempo'
  get 'educacion/remix', to: 'pages#remix'
  get 'radio/prohibidopensar', to: 'pages#prohibidopensar'
  get 'radio/elritualdelamemoria', to: 'pages#elritualdelamemoria'
  get 'radio/chicasnoches', to: 'pages#chicasnoches'
  get 'radio/elrumordeladiscordia', to: 'pages#elrumordeladiscordia'
  get 'radio/radiorevueltas', to: 'pages#radiorevueltas'
  get 'servicios/pedagogias', to: 'pages#pedagogias'
  get 'servicios/identidadverbal', to: 'pages#identidadverbal'
  get 'servicios/estrategiaverbal', to: 'pages#estrategiaverbal'
  get 'servicios/contenidoverbal', to: 'pages#contenidoverbal'

end